site_name: EPIC Developers Documentation
site_url: https://docs.epic.tech
site_author: blacktyg3r
site_description: 'EPIC Documentation'

# Repository
repo_name: docs.epic.tech
repo_url: https://github.com/EpicCash/epiccash.github.io

plugins:
    - search
    - tags

nav:
  - Welcome: index.md

  - Node (Server):
    - Introduction: node/index.md
    - Node CLI: node/cli.md
    - Node API:
      - Owner: node/owner.md
      - Foreign: node/foreign.md
      - Errors: node/errors.md
      - Mining: node/stratum.md

  - Wallet:
    - Introduction: wallet/index.md
#    - GUI Quick Guide: wallet/guide.md
    - Wallet CLI: wallet/cli.md
    - Wallet API:
      - Owner: wallet/owner.md
      - Foreign: wallet/foreign.md
      - Errors: wallet/errors.md

  - Python SDK:
    - Introduction: python_sdk/under_construction.md
#    - Node class: python_sdk/node.md
#    - Wallet class: python_sdk/wallet.md
  - Giver Of Epic:
      Introduction: giverofepic/index.md

theme:
    favicon: assets/favicon.png
    logo: assets/epic-cash-logo.png
    name: material
    custom_dir: template
    features:
        - toc.integrate
        - navigation.instant
        - navigation.tracking
        - navigation.sections
        - content.code.annotate

    palette:
    # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          accent: blue
          toggle:
            icon: material/brightness-4
            name: Switch to dark mode

    # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: indigo
          accent: light green
          toggle:
            icon: material/brightness-7
            name: Switch to light mode

    icon:
      admonition:
        note: octicons/tag-16
        abstract: octicons/checklist-16
        info: octicons/info-16
        tip: octicons/squirrel-16
        success: octicons/check-16
        question: octicons/question-16
        warning: octicons/alert-16
        failure: octicons/x-circle-16
        danger: octicons/zap-16
        bug: octicons/bug-16
        example: octicons/beaker-16
        quote: octicons/quote-16

extra_css:
    - 'assets/extra.css'

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.tilde
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - admonition
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EpicCash
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EpicCashTech
    - icon: fontawesome/brands/telegram
      link: https://t.me/EpicCash
    - icon: fontawesome/brands/reddit
      link: https://www.reddit.com/r/epiccash

copyright: Copyright &copy; 2022 @blacktyg3r